#!/usr/bin/expect -f

set passwords {
    "FTFtjpbfEXtUuTifpHqm"
    "voa1987"
}
set ip "135.181.113.243"

foreach pwd $passwords {
    puts "Trying password: '$pwd' on $ip"
    spawn ssh -o StrictHostKeyChecking=accept-new -o NumberOfPasswordPrompts=1 root@$ip "ls"
    expect {
        "password:" {
            send "$pwd\r"
            expect {
                "Permission denied" {
                    puts "FAILED"
                }
                "root@" {
                    puts "SUCCESS"
                    exit
                }
                eof {
                    puts "EOF"
                }
            }
        }
        "root@" {
             puts "SUCCESS (already in?)"
             exit
        }
    }
}
